### ISSUE TITLE
Still working on it?

### ISSUE THREAD

**Issue by MindfulLearner** [antmdh/Supremacy1914_DATAAnalyse#1]

**Comment by antmdh** [comment]
No. I don't find a way to have acces to the data without scrapping each page. It a little boring.

And for the analysis I made a post here for showing the results 
https://www.reddit.com/r/Supremacy1914/comments/yy514b/rail_gun_or_battleship_in_your_opinion/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

And here
https://www.reddit.com/r/Supremacy1914/comments/yvylt2/how_many_times_can_a_player_be_a_victim_of_a_coup/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

**Comment by MindfulLearner** [comment]
I was thinking on scraping the pages, do you think is it viable?

**Comment by antmdh** [comment]
If you scrap the data. It's will be work but you should make regularly update for having an update
